# Generated by Django 3.0.6 on 2020-05-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django-filtered-articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='markup',
            field=models.CharField(choices=[('txt', 'Plain text'), ('mkd', 'Markdown'), ('rst', 'reStructuredText')], default='txt', max_length=3),
        ),
    ]
