# Generated by Django 3.0.6 on 2020-05-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filtered_articles', '0002_article_markup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('view_unpublished_article', 'Can view an unpublished article')]},
        ),
    ]
